version: 2
updates:
- package-ecosystem: docker
  directory: /.github/test
  schedule:
    interval: weekly
  ignore:
  - dependency-name: varnish
    update-types:
    - "version-update:semver-major"

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
