version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godoclint
    - goprintffuncname
    - gosec
    - intrange
    - iotamixing
    - loggercheck
    - makezero
    - mirror
    - misspell
    - modernize
    - nakedret
    - nilerr
    - noctx
    - nilnesserr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gosec:
      excludes:
        - G104 # redundant with errcheck
        - G115 # controlled int conversions
        - G204 # subprocess launch is core functionality
        - G302 # file permissions in test cleanup
        - G304 # file reading by variable path is core functionality
        - G306 # WriteFile permissions in tests
        - G703 # temp file cleanup paths
        - G706 # normal error logging
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - revive
        text: context-as-argument
      - path: _test\.go
        linters:
          - goconst
          - noctx
