version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - contextcheck
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - errname
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - godoclint
    - goprintffuncname
    - intrange
    - iotamixing
    - loggercheck
    - mirror
    - misspell
    - modernize
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - revive
        text: context-as-argument
