extends: default

rules:
  line-length:
    max: 150
  # Multi-document Kubernetes manifests and GitHub Actions conventions
  # use indentation styles that the default rule flags incorrectly.
  indentation: disable
  # It is okay to omit the leading '---'.
  document-start: disable
  # GitHub Actions uses bare 'on:' which triggers a truthy warning.
  truthy:
    check-keys: false
