FROM varnish:6.6.2@sha256:53d615e2a6db98b9bf3c9303e5c29fc13786c7effda31f0dfc428c69f5241ab2
ARG BINARY=k8s-httpcache
COPY --chmod=755 ${BINARY} /usr/local/bin/k8s-httpcache
ENTRYPOINT ["/usr/local/bin/k8s-httpcache"]
CMD []
