FROM varnish:8.0.0@sha256:bb543e8e199894e126d12e9dabc9e23a185b2eb641f29e906a1d26d8ffe1be93
ARG BINARY=k8s-httpcache
COPY --chmod=755 ${BINARY} /usr/local/bin/k8s-httpcache
ENTRYPOINT ["/usr/local/bin/k8s-httpcache"]
CMD []
