{{- if include "k8s-httpcache.createClusterRole" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}-nodes
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
  {{- with include "k8s-httpcache.annotations" (dict "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
{{- end }}
