{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
  {{- with include "k8s-httpcache.annotations" (dict "extra" .Values.httpRoute.annotations "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.httpRoute.rules }}
    - {{- with .matches }}
      matches:
        {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 8 }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "k8s-httpcache.fullname" $ }}
          port: {{ $.Values.service.httpPort }}
    {{- end }}
{{- end }}
