{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
  {{- with include "k8s-httpcache.annotations" (dict "extra" .Values.ingress.annotations "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ include "k8s-httpcache.tpl" (dict "value" . "ctx" $) }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | quote }}
        {{- end }}
      secretName: {{ include "k8s-httpcache.tpl" (dict "value" .secretName "ctx" $) }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ include "k8s-httpcache.tpl" (dict "value" .host "ctx" $) | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "k8s-httpcache.fullname" $ }}
                port:
                  number: {{ $.Values.service.httpPort }}
          {{- end }}
    {{- end }}
{{- end }}
