{{- if .Values.istio.requestAuthentication.enabled -}}
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
  {{- with include "k8s-httpcache.annotations" (dict "extra" .Values.istio.requestAuthentication.annotations "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-httpcache.selectorLabels" . | nindent 6 }}
  {{- with .Values.istio.requestAuthentication.jwtRules }}
  jwtRules:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
{{- end }}
