{{- if .Values.istio.peerAuthentication.enabled -}}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
  {{- with include "k8s-httpcache.annotations" (dict "extra" .Values.istio.peerAuthentication.annotations "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-httpcache.selectorLabels" . | nindent 6 }}
  {{- with .Values.istio.peerAuthentication.mtls }}
  mtls:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.peerAuthentication.portLevelMtls }}
  portLevelMtls:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
{{- end }}
