{{- if .Values.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
  {{- with include "k8s-httpcache.annotations" (dict "extra" .Values.istio.virtualService.annotations "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- if .Values.istio.virtualService.hosts }}
    {{- range .Values.istio.virtualService.hosts }}
    - {{ include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | quote }}
    {{- end }}
    {{- else }}
    - {{ include "k8s-httpcache.fullname" . | quote }}
    {{- end }}
  {{- with .Values.istio.virtualService.gateways }}
  gateways:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.istio.virtualService.http }}
  http:
    {{- include "k8s-httpcache.tpl" (dict "value" .Values.istio.virtualService.http "ctx" $) | nindent 4 }}
  {{- else }}
  {{- /* Default: route all HTTP traffic to the Service. */}}
  http:
    - route:
        - destination:
            host: {{ include "k8s-httpcache.serviceFQDN" . }}
            port:
              number: {{ .Values.service.httpPort }}
  {{- end }}
  {{- with .Values.istio.virtualService.tls }}
  tls:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.virtualService.tcp }}
  tcp:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
{{- end }}
