{{- if .Values.podMonitor.enabled -}}
{{- /* Alternative to the ServiceMonitor - scrapes pods directly. Enable only one. */}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}
  namespace: {{ .Values.podMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
    {{- end }}
  {{- with include "k8s-httpcache.annotations" (dict "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-httpcache.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: http-m
      path: /metrics
      {{- with .Values.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.podMonitor.relabelings }}
      relabelings:
        {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 8 }}
      {{- end }}
{{- end }}
