apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-httpcache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-httpcache.labels" . | nindent 4 }}
  {{- with include "k8s-httpcache.annotations" (dict "extra" .Values.service.annotations "root" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- include "k8s-httpcache.tpl" (dict "value" . "ctx" $) | nindent 4 }}
  {{- end }}
  selector:
    {{- include "k8s-httpcache.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: http
    {{- if .Values.tlsCerts }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.httpsPort | default 8443 }}
      targetPort: https
    {{- end }}
    {{- if .Values.broadcast.enabled }}
    - name: http-b
      protocol: TCP
      port: {{ .Values.service.httpBroadcastPort | default 8088 }}
      targetPort: http-b
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: http-m
      protocol: TCP
      port: {{ .Values.service.httpMetricsPort | default 9101 }}
      targetPort: http-m
    {{- end }}
